services:

    DoctrineAnnotationConfiguration:
        class: \Doctrine\ORM\Configuration
        factory_class: \Doctrine\ORM\Tools\Setup
        factory_method: createAnnotationMetadataConfiguration
        arguments: [ %orm.doctrine.entities.paths%, %orm.doctrine.devmode% ]
        calls:
            - [ 'addCustomNumericFunction', [ 'RANDOM', '\WordSelector\Util\Doctrine\Random' ] ]

    DoctrineYmlConfiguration:
        class: \Doctrine\ORM\Configuration
        factory_class: \Doctrine\ORM\Tools\Setup
        factory_method: createYAMLMetadataConfiguration
        arguments: [ %orm.doctrine.yml.paths%, %orm.doctrine.devmode% ]
        calls:
            - [ 'addCustomNumericFunction', [ 'RANDOM', '\WordSelector\Util\Doctrine\Random' ] ]

    EntityManager:
        class: \Doctrine\ORM\EntityManager
        factory_class: \Doctrine\ORM\EntityManager
        factory_method: create
        arguments: [ %orm.doctrine.db%, @DoctrineYmlConfiguration ]