services:

    WordRepository:
        class: \WordSelector\Repository\WordRepository
        factory_service: EntityManager
        factory_method: getRepository
        arguments: [ WordSelector\Entity\Word ]

    WordManager:
        class: \WordSelector\Manager\WordManager
        arguments: [ '@WordRepository' ]

    WordService:
        class: \WordSelector\Service\WordService
        arguments: [ '@WordManager' ]

    WordSelector:
        class: \WordSelector\WordSelector
        arguments: [ '@WordService' ]